export const dummyData = [{
  headerSectionTitle: "Adults need around 2000 kcal a day",
  title: "New Daily Specials",
  data: [{
    special: true,
    available: true,
    popular: true,
    currency: "£",
    kcal: "229 kcal",
    desc: "Crispy bacon with sweetcorn, cheddar, roasted tomatoes,  carrot, crotonscheddar, roasted tomatoes,  carrot, crotons and caesar dressing",
    name: "dummyName",
    price: "12",
    image: "https://rs-menus-api.roocdn.com/images/896a82da-8dd7-4d65-b373-546698ac309e/image.jpeg?width=294&height=294&auto=webp&format=jpg&fit=crop",
  }, {
    // special:true,
    available: true,
    popular: true,
    currency: "£",
    kcal: "229 kcal",
    desc: "Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,  carrot, crotons and caesar dressing",
    name: "shawarma wrap with shawarma chicken DAILY SPECIAL chicken DAILY SPECIAL chicken DAILY SPECIAL",
    price: "12",
    image: "https://rs-menus-api.roocdn.com/images/896a82da-8dd7-4d65-b373-546698ac309e/image.jpeg?width=294&height=294&auto=webp&format=jpg&fit=crop",
  }, {
    // special:true,
    available: false,
    // popular:true,
    currency: "£",
    kcal: "229 kcal",
    desc: "Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,  carrot, crotons and caesar dressing",
    name: "shawarma wrap with shawarma chicken DAILY SPECIAL",
    price: "12",
    image: "https://rs-menus-api.roocdn.com/images/896a82da-8dd7-4d65-b373-546698ac309e/image.jpeg?width=294&height=294&auto=webp&format=jpg&fit=crop",
  }],
},
  {
    headerSectionTitle: "Adults need around 2000 kcal a day",
    title: "New Daily Specials",
    data: [{
      special: true,
      available: true,
      popular: true,
      currency: "£",
      kcal: "229 kcal",
      desc: "Crispy bacon with sweetcorn, cheddar, roasted tomatoes,  carrot, crotonscheddar, roasted tomatoes,  carrot, crotons and caesar dressing",
      name: "dummyName",
      price: "12",
      image: "https://rs-menus-api.roocdn.com/images/896a82da-8dd7-4d65-b373-546698ac309e/image.jpeg?width=294&height=294&auto=webp&format=jpg&fit=crop",
    }, {
      // special:true,
      available: true,
      popular: true,
      currency: "£",
      kcal: "229 kcal",
      desc: "Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,  carrot, crotons and caesar dressing",
      name: "shawarma wrap with shawarma chicken DAILY SPECIAL chicken DAILY SPECIAL chicken DAILY SPECIAL",
      price: "12",
      image: "https://rs-menus-api.roocdn.com/images/896a82da-8dd7-4d65-b373-546698ac309e/image.jpeg?width=294&height=294&auto=webp&format=jpg&fit=crop",
    }, {
      // special:true,
      available: false,
      // popular:true,
      currency: "£",
      kcal: "229 kcal",
      desc: "Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,  carrot, crotons and caesar dressing",
      name: "shawarma wrap with shawarma chicken DAILY SPECIAL",
      price: "12",
      image: "https://rs-menus-api.roocdn.com/images/896a82da-8dd7-4d65-b373-546698ac309e/image.jpeg?width=294&height=294&auto=webp&format=jpg&fit=crop",
    }],
  },{
    headerSectionTitle: "Adults need around 2000 kcal a day",
    title: "New Daily Specials",
    data: [{
      special: true,
      available: true,
      popular: true,
      currency: "£",
      kcal: "229 kcal",
      desc: "Crispy bacon with sweetcorn, cheddar, roasted tomatoes,  carrot, crotonscheddar, roasted tomatoes,  carrot, crotons and caesar dressing",
      name: "dummyName",
      price: "12",
      image: "https://rs-menus-api.roocdn.com/images/896a82da-8dd7-4d65-b373-546698ac309e/image.jpeg?width=294&height=294&auto=webp&format=jpg&fit=crop",
    }, {
      // special:true,
      available: true,
      popular: true,
      currency: "£",
      kcal: "229 kcal",
      desc: "Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,  carrot, crotons and caesar dressing",
      name: "shawarma wrap with shawarma chicken DAILY SPECIAL chicken DAILY SPECIAL chicken DAILY SPECIAL",
      price: "12",
      image: "https://rs-menus-api.roocdn.com/images/896a82da-8dd7-4d65-b373-546698ac309e/image.jpeg?width=294&height=294&auto=webp&format=jpg&fit=crop",
    }, {
      // special:true,
      available: false,
      // popular:true,
      currency: "£",
      kcal: "229 kcal",
      desc: "Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy Crispy bacon with sweetcorn, cheddar, roasted tomatoes,Crispy bacon with sweetcorn, cheddar, roasted tomatoes,  carrot, crotons and caesar dressing",
      name: "shawarma wrap with shawarma chicken DAILY SPECIAL",
      price: "12",
      image: "https://rs-menus-api.roocdn.com/images/896a82da-8dd7-4d65-b373-546698ac309e/image.jpeg?width=294&height=294&auto=webp&format=jpg&fit=crop",
    }],
  }]
