export const SCREEN_NAMES = {
  HOME_SCREEN: 'HOME_SCREEN',
  EXTRA_SCREEN: 'EXTRA_SCREEN',
  BOTTOM_NAV: 'BOTTOM_NAV',

  INFO_MODAL: 'INFO_MODAL',
  SEARCH_MODAL: 'SEARCH_MODAL',
  ACCOUNT_MODAL: 'ACCOUNT_MODAL',
  DELIVERY_MODAL: 'DELIVERY_MODAL',
  ITEM_MODAL: 'ITEM_MODAL',

  WEB_VIEW: 'WEB_VIEW',

  LOGIN: 'LOGIN',
  EMAIL_SCREEN: 'EMAIL_SCREEN',
};
