export const DUMMY = {
  LOADING: 'DUMMY/LOADING',
  SUCCESS: 'DUMMY/SUCCESS',
  FAILED: 'DUMMY/FAILED',
};


export const AUTH = {
  LOADING: 'AUTH/LOADING',
  SUCCESS: 'AUTH/SUCCESS',
  FAILED: 'AUTH/FAILED',
  CLEAR: 'AUTH/CLEAR',
};
